### ISSUE TITLE
NullPointerException running DynamoDBLocalFixture

### ISSUE THREAD

**Issue by sarnobat** [awslabs/aws-dynamodb-examples#2]
I'm running it inside Eclipse having successfully done mvn compile and mvn eclipse:eclipse.

Exception in thread "main" java.lang.NullPointerException
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess.initializeMetadataTables(SQLiteDBAccess.java:388)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess.<init>(SQLiteDBAccess.java:224)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess.<init>(SQLiteDBAccess.java:193)
	at com.amazonaws.services.dynamodbv2.local.embedded.DynamoDBEmbedded.create(DynamoDBEmbedded.java:40)
	at com.amazonaws.services.dynamodbv2.local.embedded.DynamoDBEmbedded.create(DynamoDBEmbedded.java:30)
	at com.amazonaws.services.dynamodbv2.DynamoDBLocalFixture.main(DynamoDBLocalFixture.java:33)

**Comment by sarnobat** [comment]
The workaround described here didn't work for me:
https://forums.aws.amazon.com/thread.jspa?threadID=212169

**Comment by StanSvec** [comment]
It works for me. I copied libsqlite4java-linux-amd64-1.0.392.so (using linux) file into lib directory located in my root project directory. Then only:
```groovy
System.getProperties().setProperty('sqlite4java.library.path', 'lib')
def localDynamo = DynamoDBEmbedded.create().amazonDynamoDB()
```

**Comment by sarnobat** [comment]
I no longer work on DynamoDB so I can't verify this. I'm closing the ticket - I hope someone else can reopen it if they still need help on it.

**Comment by duc-anh-tran** [comment]
> It works for me. I copied libsqlite4java-linux-amd64-1.0.392.so (using linux) file into lib directory located in my root project directory. Then only:
> 
> ```groovy
> System.getProperties().setProperty('sqlite4java.library.path', 'lib')
> def localDynamo = DynamoDBEmbedded.create().amazonDynamoDB()
> ```

Your solution reminds me that I forgot to do a project build (e.g: mvn clean install) to copy the libs to a subfolder under project root.
